# Gateway Port
server.port=8080

# Enable Eureka Locator (Allows Gateway to find services by their registered name in Eureka)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ==========================================
# MICROSERVICE ROUTING RULES
# ==========================================

# 1. User Service Routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**, /api/users/**, /api/admin/users/**

# 2. Operator Service Routes
spring.cloud.gateway.routes[1].id=operator-service
spring.cloud.gateway.routes[1].uri=lb://operator-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/operators/**, /api/plans/**, /api/admin/operators/**, /api/admin/plans/**

# 3. Recharge Service Routes
spring.cloud.gateway.routes[2].id=recharge-service
spring.cloud.gateway.routes[2].uri=lb://recharge-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recharges/**, /api/admin/recharges/**

# 4. Payment Service Routes
spring.cloud.gateway.routes[3].id=payment-service
spring.cloud.gateway.routes[3].uri=lb://payment-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/payments/**, /api/admin/payments/**

# 5. Notification Service Routes
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notifications/**, /api/admin/notifications/**
