server.port=8761
spring.application.name=discovery-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
