spring.application.name=discovery-server
# Port for Eureka Service Registry
server.port=8761

# Hostname - Production ready (Injectable via Environment Variable)
eureka.instance.hostname=${EUREKA_HOST:localhost}

# Eureka Server specific settings
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,env
