server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/omnicharge_user_db
spring.datasource.username=postgres
spring.datasource.password=Login@630

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
